//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int Feedback_id { get; set; }
        public int s_id { get; set; }
        public string s_name { get; set; }
        public int c_id { get; set; }
        public string Feedback1 { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual Student Student { get; set; }
    }
}
