//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forgot_Pass
    {
        public int ForgotPass_id { get; set; }
        public int s_id { get; set; }
        public string s_email { get; set; }
        public string reset_key { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
