//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int Q_no { get; set; }
        public string Question1 { get; set; }
        public string Option1 { get; set; }
        public string Option2 { get; set; }
        public string Option3 { get; set; }
        public string Option4 { get; set; }
        public string Correct_ans { get; set; }
        public int c_id { get; set; }
        public int Level { get; set; }
    
        public virtual Cours Cours { get; set; }
    }
}
